#!/usr/bin/env python3
"""Generate the BMC supplementary table for the stratified prompt control."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np


DATASETS = (
    "medclipseg_busi",
    "medclipseg_clinicdb",
    "medclipseg_busbra",
    "medclipseg_brisc",
    "medclipseg_covid19",
)
DISPLAY = {
    "medclipseg_busi": "BUSI",
    "medclipseg_clinicdb": "ClinicDB",
    "medclipseg_busbra": "BUS-BRA",
    "medclipseg_brisc": "BRISC",
    "medclipseg_covid19": "COVID-19",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--result-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def signed(value: float) -> str:
    return f"{value * 100:+.2f}"


def mean_std(values: list[float]) -> str:
    return f"{np.mean(values) * 100:.2f}\\pm{np.std(values, ddof=1) * 100:.2f}"


def pvalue(value: float) -> str:
    if value < 1e-6:
        return "$<10^{-6}$"
    return f"{value:.3f}".lstrip("0")


def main() -> int:
    args = parse_args()
    seed_rows = read_csv(args.result_dir / "seed_summary.csv")
    stats_rows = read_csv(args.result_dir / "casefirst_true_vs_stratified_derangement.csv")
    map_summary = read_csv(args.result_dir / "control_maps" / "stratified_derangement_v1_summary.csv")

    seed_values: dict[tuple[str, str], list[float]] = defaultdict(list)
    per_seed_dataset: dict[tuple[int, str], dict[str, float]] = defaultdict(dict)
    for row in seed_rows:
        dataset = row["dataset"]
        control = row["control"]
        value = float(row["dice_mean"])
        seed_values[(dataset, control)].append(value)
        per_seed_dataset[(int(row["seed"]), control)][dataset] = value

    stats = {
        row["dataset"]: row
        for row in stats_rows
        if row["metric"] == "dice"
    }
    changed_by_dataset: dict[str, int] = defaultdict(int)
    cases_by_dataset: dict[str, int] = defaultdict(int)
    for row in map_summary:
        dataset = row["dataset"]
        changed_by_dataset[dataset] += int(row["n_text_changed"])
        cases_by_dataset[dataset] += int(row["n_cases"])

    body = []
    for dataset in DATASETS:
        row = stats[dataset]
        body.append(
            f"{DISPLAY[dataset]} & {changed_by_dataset[dataset]}/{cases_by_dataset[dataset]} & "
            f"${mean_std(seed_values[(dataset, 'true')])}$ & "
            f"${mean_std(seed_values[(dataset, 'stratified_derangement')])}$ & "
            f"${signed(float(row['delta_true_minus_control']))}$ "
            f"[${signed(float(row['ci_low']))},{signed(float(row['ci_high']))}$] & "
            f"{pvalue(float(row['wilcoxon_p_holm']))} \\\\" 
        )

    true_macro = [
        float(np.mean([per_seed_dataset[(seed, "true")][dataset] for dataset in DATASETS]))
        for seed in (123, 456, 789)
    ]
    control_macro = [
        float(
            np.mean(
                [per_seed_dataset[(seed, "stratified_derangement")][dataset] for dataset in DATASETS]
            )
        )
        for seed in (123, 456, 789)
    ]
    macro = stats["Public-5"]
    body.append("\\midrule")
    body.append(
        f"Public-5 & {sum(changed_by_dataset.values())}/{sum(cases_by_dataset.values())} & "
        f"${mean_std(true_macro)}$ & ${mean_std(control_macro)}$ & "
        f"${signed(float(macro['delta_true_minus_control']))}$ "
        f"[${signed(float(macro['ci_low']))},{signed(float(macro['ci_high']))}$] & -- \\\\"
    )

    lines = [
        "% Auto-generated by generate_stratified_derangement_table.py.",
        "% Do not edit numerical cells manually.",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Post hoc frozen-checkpoint prompt control that permutes the complete prompt",
        "multiset within target-presence and diagnostic-class strata. Changed/N is the number",
        "of cases receiving a different text string. Dice values are percentages",
        "(mean$\\pm$sample standard deviation across three checkpoints); deltas are",
        "case-first true-minus-control effects with 95\\% bootstrap confidence intervals.",
        "Holm $p$ is the adjusted paired Wilcoxon value across the five datasets.}",
        "\\label{tab:stratified_derangement}",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{3.0pt}",
        "\\begin{tabular}{@{}lrrrrl@{}}",
        "\\toprule",
        "Dataset & Changed/N & True Dice & Stratified & $\\Delta$ [95\\% CI] & Holm $p$ \\\\",
        "\\midrule",
        *body,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
