#!/usr/bin/env python3
"""Merge Protocol V3 complexity benchmarks and generate the manuscript table."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ORDER = (
    "U-Net++",
    "RollingUNet",
    "LViT",
    "CausalCLIPSeg (R0)",
    "MedCLIPSeg (1 sample)",
    "MedCLIPSeg (official 30 samples)",
    "MedEquiSeg",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-csv", type=Path, required=True)
    parser.add_argument("--output-tex", type=Path, required=True)
    return parser.parse_args()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def latex_method(name: str) -> str:
    labels = {
        "U-Net++": r"U-Net++$^\dagger$",
        "RollingUNet": r"RollingUNet$^\dagger$",
        "LViT": "LViT",
        "CausalCLIPSeg (R0)": "CausalCLIPSeg Baseline",
        "MedCLIPSeg (1 sample)": r"MedCLIPSeg ($S=1$)",
        "MedCLIPSeg (official 30 samples)": r"MedCLIPSeg ($S=30$)",
        "MedEquiSeg": r"\textbf{\methodname{} (Ours)}",
    }
    return labels[name]


def main() -> None:
    args = parse_args()
    source_files = ("unetplusplus.csv", "rolling.csv", "lvit.csv", "r0.csv", "medclipseg.csv", "r11.csv")
    rows = []
    for filename in source_files:
        path = args.input_dir / filename
        if not path.is_file():
            raise FileNotFoundError(path)
        rows.extend(read_rows(path))
    by_method = {row["method"]: row for row in rows}
    missing = set(ORDER) - set(by_method)
    if missing:
        raise ValueError(f"Missing complexity rows: {sorted(missing)}")
    ordered = [by_method[name] for name in ORDER]

    args.output_csv.parent.mkdir(parents=True, exist_ok=True)
    with args.output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(ordered[0]))
        writer.writeheader()
        writer.writerows(ordered)

    lines = [
        "% Auto-generated by paper/analysis/generate_complexity_table.py",
        r"\begin{table}[!t]",
        r"\centering",
        r"\caption{Instantiated model size and synchronized single-image inference cost. Parameter columns count all modules stored in each instantiated model; they are not pruned to output-connected subgraphs. Requires-grad counts follow the checkpoint implementation. All timing measurements use batch size 1, FP32, $224\times224$ input, and an NVIDIA GeForce RTX 4090. Values are mean$\pm$standard deviation after warm-up; data loading and post-processing are excluded. Cached text lookup is included for \methodname{} and LViT, whereas MedCLIPSeg runs its online UniMedCLIP/BiomedBERT towers. $S$ is the number of probabilistic samples requested from the released MedCLIPSeg forward path. A dagger marks image-only methods.}",
        r"\label{tab:complexity}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.0pt}",
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"Method & Params (M) & Trainable (M) & ms/image & Images/s & Peak MB \\",
        r"\midrule",
    ]
    for row in ordered:
        latency = f"{float(row['latency_mean_ms']):.2f}$\\pm${float(row['latency_std_ms']):.2f}"
        lines.append(
            " & ".join(
                [
                    latex_method(row["method"]),
                    f"{float(row['parameters_million']):.2f}",
                    f"{float(row['trainable_parameters_million']):.2f}",
                    latency,
                    f"{float(row['throughput_images_s']):.2f}",
                    f"{float(row['peak_gpu_memory_mb']):.0f}",
                ]
            )
            + r" \\" 
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    args.output_tex.parent.mkdir(parents=True, exist_ok=True)
    args.output_tex.write_text("\n".join(lines), encoding="utf-8")
    print(f"rows={len(ordered)} csv={args.output_csv} tex={args.output_tex}")


if __name__ == "__main__":
    main()
