#!/usr/bin/env python3
"""Generate manuscript assets only after the strict ablation is complete."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import statistics
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SEEDS = (123, 456, 789)
DATASETS = (
    ("BUSI", "BUSI"),
    ("ClinicDB", "ClinicDB"),
    ("BUS-BRA", "BUS-BRA"),
    ("BRISC", "BRISC"),
    ("COVID-19", "COVID-19"),
)


@dataclass(frozen=True)
class Method:
    run_id: str
    label: str
    biomedclip: str
    atconv: str
    shared_plan: str
    rewrite: str


METHODS = (
    Method("V3_ABL_BASE", "Base model", "No", "No", "No", "No"),
    Method("V3_ABL_BIOMED", r"Base $+$ BioMedCLIP", "Yes", "No", "No", "No"),
    Method("V3_ABL_ATCONV", r"Base $+$ ATConv", "No", "Yes", "No", "No"),
    Method(
        "V3_ABL_BIOMED_ATCONV",
        r"Base $+$ BioMedCLIP $+$ ATConv",
        "Yes",
        "Yes",
        "No",
        "No",
    ),
    Method(
        "V3_ABL_SHARED_NR",
        r"\norewrite{}",
        "Yes",
        "Yes",
        "Yes",
        "No",
    ),
    Method(
        "V3_ABL_EQUIPROMPT",
        r"\textbf{\methodname{} (Ours)}",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
    ),
)
METRICS = ("dice", "iou")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def mean_std(values: list[float]) -> tuple[float, float]:
    return statistics.mean(values), statistics.stdev(values)


def fmt(mean: float, std: float, rank: int) -> str:
    value = rf"${100 * mean:.2f}\pm{100 * std:.2f}$"
    if rank == 0:
        return rf"\textbf{{{value}}}"
    if rank == 1:
        return rf"\underline{{{value}}}"
    return value


def read_seed_rows(path: Path) -> dict[tuple[str, str, int], dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    keyed: dict[tuple[str, str, int], dict[str, str]] = {}
    for row in rows:
        key = (row["run_id"], row["dataset"], int(row["seed"]))
        if key in keyed:
            raise ValueError(f"Duplicate strict-ablation result: {key}")
        keyed[key] = row
    return keyed


def expected_keys() -> set[tuple[str, str, int]]:
    return {
        (method.run_id, dataset, seed)
        for method in METHODS
        for dataset, _ in DATASETS
        for seed in SEEDS
    }


def build_stats(
    rows: dict[tuple[str, str, int], dict[str, str]],
) -> dict[tuple[str, str, str], tuple[float, float]]:
    stats: dict[tuple[str, str, str], tuple[float, float]] = {}
    for method in METHODS:
        for dataset, _ in DATASETS:
            for metric in METRICS:
                values = [float(rows[(method.run_id, dataset, seed)][metric]) for seed in SEEDS]
                stats[(method.run_id, dataset, metric)] = mean_std(values)
        for metric in METRICS:
            seed_macros = [
                statistics.mean(
                    float(rows[(method.run_id, dataset, seed)][metric])
                    for dataset, _ in DATASETS
                )
                for seed in SEEDS
            ]
            stats[(method.run_id, "Public-5 macro", metric)] = mean_std(seed_macros)
    return stats


def rank_map(
    stats: dict[tuple[str, str, str], tuple[float, float]],
) -> dict[tuple[str, str, str], int]:
    ranks: dict[tuple[str, str, str], int] = {}
    for dataset in [name for name, _ in DATASETS] + ["Public-5 macro"]:
        for metric in METRICS:
            ordered = sorted(
                METHODS,
                key=lambda method: stats[(method.run_id, dataset, metric)][0],
                reverse=True,
            )
            for rank, method in enumerate(ordered):
                ranks[(method.run_id, dataset, metric)] = rank
    return ranks


def latex_table(
    stats: dict[tuple[str, str, str], tuple[float, float]],
    ranks: dict[tuple[str, str, str], int],
) -> str:
    lines = [
        "% Auto-generated by generate_medequiseg_factorial_manuscript_assets.py.",
        "% Do not edit numerical cells manually.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Strict three-seed component and prompt-consistency ablation on the five public datasets. All rows use the locked Protocol V3 manifests, 100 epochs, and the same held-out evaluation. Values are Dice and IoU percentages (mean$\pm$sample standard deviation). Bold and underline denote the best and second-best configuration within each dataset and metric. The shared-plan rows are matched exactly except for prompt rewriting.}",
        r"\label{tab:medequiseg_factorial}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.8pt}",
        r"\begin{tabular}{@{}lcccc@{}}",
        r"\toprule",
        r"Configuration & BioMedCLIP & ATConv & Shared plan & Rewrite \\",
        r"\midrule",
    ]
    for method in METHODS:
        lines.append(
            f"{method.label} & {method.biomedclip} & {method.atconv} & "
            f"{method.shared_plan} & {method.rewrite} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            "",
            r"\vspace{4pt}",
            r"\begin{tabular}{@{}llrrrrrr@{}}",
            r"\toprule",
            r"Configuration & Metric & BUSI & ClinicDB & BUS-BRA & BRISC & COVID-19 & Public-5 \\",
            r"\midrule",
        ]
    )
    datasets = [name for name, _ in DATASETS] + ["Public-5 macro"]
    for method_index, method in enumerate(METHODS):
        for metric_index, metric in enumerate(METRICS):
            label = method.label if metric_index == 0 else ""
            metric_label = "Dice" if metric == "dice" else "IoU"
            cells = []
            for dataset in datasets:
                mean, std = stats[(method.run_id, dataset, metric)]
                cells.append(fmt(mean, std, ranks[(method.run_id, dataset, metric)]))
            lines.append(f"{label} & {metric_label} & " + " & ".join(cells) + r" \\")
        if method_index != len(METHODS) - 1:
            lines.append(r"\addlinespace[1pt]")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def latex_compact_table(
    stats: dict[tuple[str, str, str], tuple[float, float]],
    ranks: dict[tuple[str, str, str], int],
) -> str:
    labels = {
        "V3_ABL_BASE": "Base model",
        "V3_ABL_BIOMED": r"$+$ BioMedCLIP",
        "V3_ABL_ATCONV": r"$+$ ATConv",
        "V3_ABL_BIOMED_ATCONV": r"$+$ BioMedCLIP $+$ ATConv",
        "V3_ABL_SHARED_NR": r"$+$ Shared plan (no rewrite)",
        "V3_ABL_EQUIPROMPT": r"\textbf{\methodname{} (Ours)}",
    }

    def mark(value: str) -> str:
        return r"\checkmark" if value == "Yes" else "--"

    lines = [
        "% Auto-generated by generate_medequiseg_factorial_manuscript_assets.py.",
        "% Do not edit numerical cells manually.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Strict three-seed ordered component ablation on the five public datasets. Values are equal-dataset Public-5 Dice and IoU percentages (mean$\pm$sample standard deviation). BMC denotes BioMedCLIP conditioning; Plan denotes the shared deterministic training plan. Bold and underline identify the best and second-best configurations. The complete per-dataset matrix is reported in Supplementary Table S10.}",
        r"\label{tab:medequiseg_factorial}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3.2pt}",
        r"\begin{tabular}{@{}lccccrr@{}}",
        r"\toprule",
        r"Configuration & BMC & ATConv & Plan & Rewrite & Dice & IoU \\",
        r"\midrule",
    ]
    for method in METHODS:
        dice = stats[(method.run_id, "Public-5 macro", "dice")]
        iou = stats[(method.run_id, "Public-5 macro", "iou")]
        lines.append(
            f"{labels[method.run_id]} & {mark(method.biomedclip)} & {mark(method.atconv)} & "
            f"{mark(method.shared_plan)} & {mark(method.rewrite)} & "
            f"{fmt(*dice, ranks[(method.run_id, 'Public-5 macro', 'dice')])} & "
            f"{fmt(*iou, ranks[(method.run_id, 'Public-5 macro', 'iou')])}" + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def latex_detail_table(
    stats: dict[tuple[str, str, str], tuple[float, float]],
    ranks: dict[tuple[str, str, str], int],
) -> str:
    labels = {
        "V3_ABL_BASE": "Base",
        "V3_ABL_BIOMED": r"$+$ BioMedCLIP",
        "V3_ABL_ATCONV": r"$+$ ATConv",
        "V3_ABL_BIOMED_ATCONV": r"$+$ BioMedCLIP $+$ ATConv",
        "V3_ABL_SHARED_NR": r"$+$ Shared plan (no rewrite)",
        "V3_ABL_EQUIPROMPT": r"\textbf{\methodname{} (Ours)}",
    }
    lines = [
        "% Auto-generated by generate_medequiseg_factorial_manuscript_assets.py.",
        "% Do not edit numerical cells manually.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Complete strict three-seed component ablation. Values are Dice and IoU percentages (mean$\pm$sample standard deviation). Bold and underline identify the best and second-best configuration within each dataset and metric.}",
        r"\label{tab:medequiseg_factorial_detail}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3.0pt}",
    ]
    panels = (
        ("BUSI", "ClinicDB", "BUS-BRA"),
        ("BRISC", "COVID-19", "Public-5 macro"),
    )
    for panel_index, datasets in enumerate(panels):
        if panel_index:
            lines.extend(["", r"\vspace{4pt}"])
        headers = ["Public-5" if dataset == "Public-5 macro" else dataset for dataset in datasets]
        lines.extend(
            [
                r"\begin{tabular}{@{}llrrr@{}}",
                r"\toprule",
                "Configuration & Metric & " + " & ".join(headers) + r" \\",
                r"\midrule",
            ]
        )
        for method_index, method in enumerate(METHODS):
            for metric_index, metric in enumerate(METRICS):
                label = labels[method.run_id] if metric_index == 0 else ""
                metric_label = "Dice" if metric == "dice" else "IoU"
                cells = [
                    fmt(
                        *stats[(method.run_id, dataset, metric)],
                        ranks[(method.run_id, dataset, metric)],
                    )
                    for dataset in datasets
                ]
                lines.append(f"{label} & {metric_label} & " + " & ".join(cells) + r" \\")
            if method_index != len(METHODS) - 1:
                lines.append(r"\addlinespace[1pt]")
        lines.extend([r"\bottomrule", r"\end{tabular}"])
    lines.extend([r"\end{table}", ""])
    return "\n".join(lines)


def markdown_summary(
    stats: dict[tuple[str, str, str], tuple[float, float]], source_hash: str
) -> str:
    lines = [
        "# Strict MedEquiSeg Factorial Ablation",
        "",
        f"- Source SHA-256: `{source_hash}`",
        "- Completeness gate: `90/90` unique dataset-model-seed cells",
        "- Seeds: `123, 456, 789`",
        "- Datasets: BUSI, ClinicDB, BUS-BRA, BRISC, COVID-19",
        "",
        "| Configuration | Public-5 Dice (%) | Public-5 IoU (%) |",
        "|---|---:|---:|",
    ]
    for method in METHODS:
        dice = stats[(method.run_id, "Public-5 macro", "dice")]
        iou = stats[(method.run_id, "Public-5 macro", "iou")]
        label = method.label.replace(r"\textbf{", "").replace(r"\methodname{} (Ours)}", "MedEquiSeg")
        label = label.replace(r"\norewrite{}", "MedEquiSeg w/o Prompt Rewrite")
        label = label.replace("$+$", "+")
        lines.append(
            f"| {label} | {100 * dice[0]:.2f} +/- {100 * dice[1]:.2f} | "
            f"{100 * iou[0]:.2f} +/- {100 * iou[1]:.2f} |"
        )
    lines.extend(["", "## Exact-plan rewrite contrast", ""])
    for metric in METRICS:
        equip = stats[("V3_ABL_EQUIPROMPT", "Public-5 macro", metric)][0]
        no_rewrite = stats[("V3_ABL_SHARED_NR", "Public-5 macro", metric)][0]
        lines.append(
            f"- Public-5 macro {metric.upper()}: MedEquiSeg - no rewrite = "
            f"{100 * (equip - no_rewrite):+.2f} pp."
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--seed-metrics",
        type=Path,
        default=ROOT / "paper/results/medequiseg_factorial_public5_20260715/seed_metrics.csv",
    )
    parser.add_argument(
        "--latex-output",
        type=Path,
        default=ROOT / "paper/latex/bmc_work/bmc_factorial_ablation_table.tex",
    )
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=ROOT / "paper/results/medequiseg_factorial_public5_20260715/manuscript_summary.md",
    )
    parser.add_argument(
        "--detail-latex-output",
        type=Path,
        default=ROOT / "paper/latex/bmc_work/bmc_factorial_ablation_detail_table.tex",
    )
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    rows = read_seed_rows(args.seed_metrics)
    expected = expected_keys()
    observed = set(rows)
    missing = sorted(expected - observed)
    unexpected = sorted(observed - expected)
    print(f"strict_ablation_complete={len(observed & expected)}/{len(expected)}")
    if missing:
        print(f"missing={len(missing)}")
        for key in missing[:12]:
            print("MISSING", *key)
    if unexpected:
        print(f"unexpected={len(unexpected)}")
        for key in unexpected[:12]:
            print("UNEXPECTED", *key)
    if missing or unexpected:
        raise SystemExit("Refusing to generate manuscript assets from an incomplete or mixed result set.")
    if args.check_only:
        return

    stats = build_stats(rows)
    ranks = rank_map(stats)
    source_hash = sha256(args.seed_metrics)
    args.latex_output.parent.mkdir(parents=True, exist_ok=True)
    args.detail_latex_output.parent.mkdir(parents=True, exist_ok=True)
    args.summary_output.parent.mkdir(parents=True, exist_ok=True)
    args.latex_output.write_text(latex_compact_table(stats, ranks), encoding="utf-8")
    args.detail_latex_output.write_text(latex_detail_table(stats, ranks), encoding="utf-8")
    args.summary_output.write_text(markdown_summary(stats, source_hash), encoding="utf-8")
    manifest = {
        "status": "complete",
        "cells": len(expected),
        "source": str(args.seed_metrics),
        "source_sha256": source_hash,
        "latex_output": str(args.latex_output),
        "detail_latex_output": str(args.detail_latex_output),
        "summary_output": str(args.summary_output),
    }
    manifest_path = args.summary_output.with_name("manuscript_asset_manifest.json")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"latex={args.latex_output}")
    print(f"detail_latex={args.detail_latex_output}")
    print(f"summary={args.summary_output}")
    print(f"manifest={manifest_path}")


if __name__ == "__main__":
    main()
